/**
 * NCERT / CBSE chapter names by subject and class (grades 6–12).
 * Stable curriculum — used as the default chapter catalog for Indian schools.
 */
export const CBSE_CHAPTERS: Record<string, Partial<Record<number, readonly string[]>>> = {
  Science: {
    6: [
      'Food: Where Does It Come From?',
      'Components of Food',
      'Fibre to Fabric',
      'Sorting Materials into Groups',
      'Separation of Substances',
      'Changes Around Us',
      'Getting to Know Plants',
      'Body Movements',
      'The Living Organisms — Characteristics and Habitats',
      'Motion and Measurement of Distances',
      'Light, Shadows and Reflections',
      'Electricity and Circuits',
      'Fun with Magnets',
      'Water',
      'Air Around Us',
      'Garbage In, Garbage Out',
    ],
    7: [
      'Nutrition in Plants',
      'Nutrition in Animals',
      'Fibre to Fabric',
      'Heat',
      'Acids, Bases and Salts',
      'Physical and Chemical Changes',
      'Weather, Climate and Adaptations of Animals to Climate',
      'Winds, Storms and Cyclones',
      'Soil',
      'Respiration in Organisms',
      'Transportation in Animals and Plants',
      'Reproduction in Plants',
      'Motion and Time',
      'Electric Current and Its Effects',
      'Light',
      'Water: A Precious Resource',
      'Forests: Our Lifeline',
      'Wastewater Story',
    ],
    8: [
      'Crop Production and Management',
      'Microorganisms: Friend and Foe',
      'Synthetic Fibres and Plastics',
      'Materials: Metals and Non-Metals',
      'Coal and Petroleum',
      'Combustion and Flame',
      'Conservation of Plants and Animals',
      'Cell — Structure and Functions',
      'Reproduction in Animals',
      'Reaching the Age of Adolescence',
      'Force and Pressure',
      'Friction',
      'Sound',
      'Chemical Effects of Electric Current',
      'Some Natural Phenomena',
      'Light',
      'Stars and the Solar System',
      'Pollution of Air and Water',
    ],
    9: [
      'Matter in Our Surroundings',
      'Is Matter Around Us Pure?',
      'Atoms and Molecules',
      'Structure of the Atom',
      'The Fundamental Unit of Life',
      'Tissues',
      'Diversity in Living Organisms',
      'Motion',
      'Force and Laws of Motion',
      'Gravitation',
      'Work and Energy',
      'Sound',
      'Why Do We Fall Ill?',
      'Natural Resources',
      'Improvement in Food Resources',
    ],
    10: [
      'Chemical Reactions and Equations',
      'Acids, Bases and Salts',
      'Metals and Non-metals',
      'Carbon and its Compounds',
      'Life Processes',
      'Control and Coordination',
      'How do Organisms Reproduce?',
      'Heredity and Evolution',
      'Light — Reflection and Refraction',
      'The Human Eye and the Colourful World',
      'Electricity',
      'Magnetic Effects of Electric Current',
      'Our Environment',
    ],
  },
  Mathematics: {
    6: [
      'Knowing Our Numbers',
      'Whole Numbers',
      'Playing with Numbers',
      'Basic Geometrical Ideas',
      'Understanding Elementary Shapes',
      'Integers',
      'Fractions',
      'Decimals',
      'Data Handling',
      'Mensuration',
      'Algebra',
      'Ratio and Proportion',
      'Symmetry',
      'Practical Geometry',
    ],
    7: [
      'Integers',
      'Fractions and Decimals',
      'Data Handling',
      'Simple Equations',
      'Lines and Angles',
      'The Triangle and its Properties',
      'Congruence of Triangles',
      'Comparing Quantities',
      'Rational Numbers',
      'Perimeter and Area',
      'Algebraic Expressions',
      'Exponents and Powers',
      'Symmetry',
      'Visualising Solid Shapes',
    ],
    8: [
      'Rational Numbers',
      'Linear Equations in One Variable',
      'Understanding Quadrilaterals',
      'Practical Geometry',
      'Data Handling',
      'Squares and Square Roots',
      'Cubes and Cube Roots',
      'Comparing Quantities',
      'Algebraic Expressions and Identities',
      'Visualising Solid Shapes',
      'Mensuration',
      'Exponents and Powers',
      'Direct and Inverse Proportions',
      'Factorisation',
      'Introduction to Graphs',
    ],
    9: [
      'Number Systems',
      'Polynomials',
      'Coordinate Geometry',
      'Linear Equations in Two Variables',
      'Introduction to Euclid\'s Geometry',
      'Lines and Angles',
      'Triangles',
      'Quadrilaterals',
      'Circles',
      'Heron\'s Formula',
      'Surface Areas and Volumes',
      'Statistics',
    ],
    10: [
      'Real Numbers',
      'Polynomials',
      'Pair of Linear Equations in Two Variables',
      'Quadratic Equations',
      'Arithmetic Progressions',
      'Triangles',
      'Coordinate Geometry',
      'Introduction to Trigonometry',
      'Some Applications of Trigonometry',
      'Circles',
      'Areas Related to Circles',
      'Surface Areas and Volumes',
      'Statistics',
      'Probability',
    ],
    11: [
      'Sets',
      'Relations and Functions',
      'Trigonometric Functions',
      'Complex Numbers and Quadratic Equations',
      'Linear Inequalities',
      'Permutations and Combinations',
      'Binomial Theorem',
      'Sequences and Series',
      'Straight Lines',
      'Conic Sections',
      'Introduction to Three Dimensional Geometry',
      'Limits and Derivatives',
      'Statistics',
      'Probability',
    ],
    12: [
      'Relations and Functions',
      'Inverse Trigonometric Functions',
      'Matrices',
      'Determinants',
      'Continuity and Differentiability',
      'Application of Derivatives',
      'Integrals',
      'Application of Integrals',
      'Differential Equations',
      'Vector Algebra',
      'Three Dimensional Geometry',
      'Linear Programming',
      'Probability',
    ],
  },
  Physics: {
    11: [
      'Physical World',
      'Units and Measurements',
      'Motion in a Straight Line',
      'Motion in a Plane',
      'Laws of Motion',
      'Work, Energy and Power',
      'System of Particles and Rotational Motion',
      'Gravitation',
      'Mechanical Properties of Solids',
      'Mechanical Properties of Fluids',
      'Thermal Properties of Matter',
      'Thermodynamics',
      'Kinetic Theory',
      'Oscillations',
      'Waves',
    ],
    12: [
      'Electric Charges and Fields',
      'Electrostatic Potential and Capacitance',
      'Current Electricity',
      'Moving Charges and Magnetism',
      'Magnetism and Matter',
      'Electromagnetic Induction',
      'Alternating Current',
      'Electromagnetic Waves',
      'Ray Optics and Optical Instruments',
      'Wave Optics',
      'Dual Nature of Radiation and Matter',
      'Atoms',
      'Nuclei',
      'Semiconductor Electronics',
    ],
  },
  Chemistry: {
    11: [
      'Some Basic Concepts of Chemistry',
      'Structure of Atom',
      'Classification of Elements and Periodicity in Properties',
      'Chemical Bonding and Molecular Structure',
      'Thermodynamics',
      'Equilibrium',
      'Redox Reactions',
      'Organic Chemistry — Some Basic Principles and Techniques',
      'Hydrocarbons',
    ],
    12: [
      'The Solid State',
      'Solutions',
      'Electrochemistry',
      'Chemical Kinetics',
      'Surface Chemistry',
      'General Principles and Processes of Isolation of Elements',
      'The p-Block Elements',
      'The d- and f-Block Elements',
      'Coordination Compounds',
      'Haloalkanes and Haloarenes',
      'Alcohols, Phenols and Ethers',
      'Aldehydes, Ketones and Carboxylic Acids',
      'Amines',
      'Biomolecules',
    ],
  },
  Biology: {
    11: [
      'The Living World',
      'Biological Classification',
      'Plant Kingdom',
      'Animal Kingdom',
      'Morphology of Flowering Plants',
      'Anatomy of Flowering Plants',
      'Structural Organisation in Animals',
      'Cell: The Unit of Life',
      'Biomolecules',
      'Cell Cycle and Cell Division',
      'Photosynthesis in Higher Plants',
      'Respiration in Plants',
      'Plant Growth and Development',
      'Breathing and Exchange of Gases',
      'Body Fluids and Circulation',
      'Excretory Products and their Elimination',
      'Locomotion and Movement',
      'Neural Control and Coordination',
      'Chemical Coordination and Integration',
    ],
    12: [
      'Reproduction in Organisms',
      'Sexual Reproduction in Flowering Plants',
      'Human Reproduction',
      'Reproductive Health',
      'Principles of Inheritance and Variation',
      'Molecular Basis of Inheritance',
      'Evolution',
      'Human Health and Disease',
      'Microbes in Human Welfare',
      'Biotechnology: Principles and Processes',
      'Biotechnology and its Applications',
      'Organisms and Populations',
      'Ecosystem',
      'Biodiversity and Conservation',
    ],
  },
  'Social Science': {
    6: [
      'Introduction: What, Where, How and When?',
      'From Hunting-Gathering to Growing Food',
      'In the Earliest Cities',
      'What Books and Burials Tell Us',
      'Kingdoms, Kings and an Early Republic',
      'New Questions and Ideas',
      'Ashoka, The Emperor Who Gave Up War',
      'Vital Villages, Thriving Towns',
      'Traders, Kings and Pilgrims',
      'New Empires and Kingdoms',
      'Buildings, Paintings and Books',
      'Understanding Diversity',
      'Diversity and Discrimination',
      'What is Government?',
      'Key Elements of a Democratic Government',
      'Panchayati Raj',
      'Rural Administration',
      'Urban Administration',
      'Rural Livelihoods',
      'Urban Livelihoods',
      'The Earth in the Solar System',
      'Globe: Latitudes and Longitudes',
      'Motions of the Earth',
      'Maps',
      'Major Domains of the Earth',
      'Major Landforms of the Earth',
      'Our Country — India',
      'India: Climate, Vegetation and Wildlife',
    ],
    7: [
      'Tracing Changes Through a Thousand Years',
      'New Kings and Kingdoms',
      'The Delhi Sultans',
      'The Mughal Empire',
      'Rulers and Buildings',
      'Towns, Traders and Craftspersons',
      'Tribes, Nomads and Settled Communities',
      'Devotional Paths to the Divine',
      'The Making of Regional Cultures',
      'Eighteenth-Century Political Formations',
      'On Equality',
      'Role of the Government in Health',
      'How the State Government Works',
      'Growing up as Boys and Girls',
      'Women Change the World',
      'Understanding Media',
      'Understanding Advertising',
      'Markets Around Us',
      'A Shirt in the Market',
      'Environment',
      'Inside Our Earth',
      'Our Changing Earth',
      'Air',
      'Water',
      'Natural Vegetation and Wildlife',
      'Human Environment — Settlement, Transport and Communication',
      'Human Environment Interactions — The Tropical and the Subtropical Region',
      'Life in the Deserts',
    ],
    8: [
      'How, When and Where',
      'From Trade to Territory',
      'Ruling the Countryside',
      'Tribals, Dikus and the Vision of a Golden Age',
      'When People Rebel',
      'Colonialism and the City',
      'Weavers, Iron Smelters and Factory Owners',
      'Civilising the Native, Educating the Nation',
      'Women, Caste and Reform',
      'The Changing World of Visual Arts',
      'The Making of the National Movement',
      'India After Independence',
      'The Indian Constitution',
      'Understanding Secularism',
      'Why Do We Need a Parliament?',
      'Understanding Laws',
      'Understanding Our Criminal Justice System',
      'Understanding Marginalisation',
      'Confronting Marginalisation',
      'Public Facilities',
      'Law and Social Justice',
      'Resources',
      'Land, Soil, Water, Natural Vegetation and Wildlife Resources',
      'Mineral and Power Resources',
      'Agriculture',
      'Industries',
      'Human Resources',
    ],
    9: [
      'The French Revolution',
      'Socialism in Europe and the Russian Revolution',
      'Nazism and the Rise of Hitler',
      'Forest Society and Colonialism',
      'Pastoralists in the Modern World',
      'Peasants and Farmers',
      'History and Sport: The Story of Cricket',
      'Clothing: A Social History',
      'India — Size and Location',
      'Physical Features of India',
      'Drainage',
      'Climate',
      'Natural Vegetation and Wildlife',
      'Population',
      'What is Democracy? Why Democracy?',
      'Constitutional Design',
      'Electoral Politics',
      'Working of Institutions',
      'Democratic Rights',
      'The Story of Village Palampur',
      'People as Resource',
      'Poverty as a Challenge',
      'Food Security in India',
    ],
    10: [
      'The Rise of Nationalism in Europe',
      'Nationalism in India',
      'The Making of a Global World',
      'The Age of Industrialisation',
      'Print Culture and the Modern World',
      'Resources and Development',
      'Forest and Wildlife Resources',
      'Water Resources',
      'Agriculture',
      'Minerals and Energy Resources',
      'Manufacturing Industries',
      'Lifelines of National Economy',
      'Power Sharing',
      'Federalism',
      'Gender, Religion and Caste',
      'Political Parties',
      'Outcomes of Democracy',
      'Development',
      'Sectors of the Indian Economy',
      'Money and Credit',
      'Globalisation and the Indian Economy',
      'Consumer Rights',
    ],
  },
  History: {
    6: ['What, Where, How and When?', 'From Hunting-Gathering to Growing Food', 'In the Earliest Cities'],
    7: ['Tracing Changes Through a Thousand Years', 'New Kings and Kingdoms', 'The Delhi Sultans', 'The Mughal Empire'],
    8: ['How, When and Where', 'From Trade to Territory', 'Ruling the Countryside', 'When People Rebel'],
    9: ['The French Revolution', 'Socialism in Europe and the Russian Revolution', 'Nazism and the Rise of Hitler'],
    10: ['The Rise of Nationalism in Europe', 'Nationalism in India', 'The Making of a Global World'],
    11: ['Writing and City Life', 'An Empire Across Three Continents', 'Nomadic Empires'],
    12: ['Bricks, Beads and Bones', 'Kings, Farmers and Towns', 'Kinship, Caste and Class'],
  },
  Geography: {
    6: ['The Earth in the Solar System', 'Globe: Latitudes and Longitudes', 'Maps', 'Our Country — India'],
    7: ['Environment', 'Inside Our Earth', 'Our Changing Earth', 'Air', 'Water'],
    8: ['Resources', 'Agriculture', 'Industries', 'Human Resources'],
    9: ['India — Size and Location', 'Physical Features of India', 'Climate', 'Population'],
    10: ['Resources and Development', 'Water Resources', 'Agriculture', 'Manufacturing Industries'],
    11: ['Geography as a Discipline', 'The Origin and Evolution of the Earth', 'Landforms'],
    12: ['Human Geography: Nature and Scope', 'The World Population', 'Migration'],
  },
  English: {
    6: ['Who Did Patrick\'s Homework?', 'How the Dog Found Himself a New Master!', 'Taro\'s Reward', 'An Indian-American Woman in Space'],
    7: ['Three Questions', 'A Gift of Chappals', 'Gopal and the Hilsa Fish', 'The Ashes That Made Trees Bloom'],
    8: ['The Best Christmas Present in the World', 'The Tsunami', 'Glimpses of the Past', 'Bepin Choudhury\'s Lapse of Memory'],
    9: ['The Fun They Had', 'The Sound of Music', 'The Little Girl', 'A Truly Beautiful Mind'],
    10: ['A Letter to God', 'Nelson Mandela: Long Walk to Freedom', 'Two Stories about Flying', 'From the Diary of Anne Frank'],
    11: ['The Portrait of a Lady', 'We\'re Not Afraid to Die', 'Discovering Tut: the Saga Continues'],
    12: ['The Last Lesson', 'Lost Spring', 'Deep Water', 'The Rattrap'],
  },
  Hindi: {
    6: ['वह चिड़िया जो', 'बचपन', 'नाना-नानी की कहानी', 'साथी हाथ बढ़ाना'],
    7: ['हम पंछी उन्मुक्त गगन के', 'दादी माँ', 'हिमालय की बेटियाँ', 'कठपुतली'],
    8: ['ध्वनि', 'लाख की चूड़ियाँ', 'बस की यात्रा', 'दीवानों की हस्ती'],
    9: ['दो बैलों की कथा', 'ल्हासा की ओर', 'उपभोक्तावाद की संस्कृति', 'साँवले सपनों की याद'],
    10: ['सूरदास के पद', 'राम-लक्ष्मण-परशुराम संवाद', 'सवैया और कवित्त', 'आत्मकथ्य'],
    11: ['कबीर — साखी', 'मीरा — पद', 'तुलसीदास — रामचरितमानस'],
    12: ['कबीर — साखी', 'मीरा — पद', 'सूरदास — पद'],
  },
  'Computer Science': {
    6: ['Introduction to Computers', 'Working with MS Paint', 'More on Scratch'],
    7: ['Programming Language', 'Editing Text in Microsoft Word', 'Microsoft PowerPoint'],
    8: ['Networking Concepts', 'Introduction to HTML', 'Introduction to Scratch'],
    9: ['Basics of Information Technology', 'Cyber Safety', 'Office Tools', 'Scratch or Python Basics'],
    10: ['Internet Basics', 'HTML', 'Python Programming Basics', 'Database Concepts'],
    11: ['Computer System', 'Encoding Schemes and Number System', 'Emerging Trends', 'Problem Solving Methodology'],
    12: ['Computational Thinking and Programming', 'Computer Networks', 'Database Management'],
  },
  Economics: {
    9: ['The Story of Village Palampur', 'People as Resource', 'Poverty as a Challenge', 'Food Security in India'],
    10: ['Development', 'Sectors of the Indian Economy', 'Money and Credit', 'Globalisation and the Indian Economy'],
    11: ['Introduction', 'Collection of Data', 'Organisation of Data', 'Presentation of Data'],
    12: ['Introduction to Microeconomics', 'Consumer\'s Equilibrium', 'Demand', 'National Income and Related Aggregates'],
  },
  'Political Science': {
    9: ['What is Democracy? Why Democracy?', 'Constitutional Design', 'Electoral Politics', 'Democratic Rights'],
    10: ['Power Sharing', 'Federalism', 'Political Parties', 'Outcomes of Democracy'],
    11: ['Constitution: Why and How?', 'Rights in the Indian Constitution', 'Election and Representation'],
    12: ['The Cold War Era', 'US Hegemony in World Politics', 'Politics in India since Independence'],
  },
};

export function getCbseChapters(grade: number, subject: string): readonly string[] {
  return CBSE_CHAPTERS[subject]?.[grade] ?? [];
}
