// PPTX Builder — Template-first slide generation using pptxgenjs
// Takes structured JSON from LLM and injects into pre-designed templates
// This is the key cost optimization: LLM generates content only, layout is deterministic
import PptxGenJS from 'pptxgenjs';
import { SLIDE_TEMPLATES, COLORS } from './templates';
import type { PresentationData, SlideData } from './shared';
import path from 'path';
import fs from 'fs';

const OUTPUT_DIR = path.join(process.cwd(), 'output');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

function addTitleSlide(pptx: PptxGenJS, slide: SlideData) {
  const tmpl = SLIDE_TEMPLATES['title'];
  const s = pptx.addSlide();
  s.background = { color: tmpl.background.color };

  // Decorative accent bar at top
  s.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: '100%', h: 0.08,
    fill: { color: COLORS.accent },
  });

  // Title
  s.addText(slide.title, {
    x: tmpl.titleConfig.x, y: tmpl.titleConfig.y,
    w: tmpl.titleConfig.w, h: tmpl.titleConfig.h,
    fontSize: tmpl.titleConfig.fontSize,
    color: tmpl.titleConfig.color,
    bold: true,
    align: 'center',
    fontFace: 'Arial',
  });

  // Subtitle
  if (slide.bodyText && tmpl.bodyConfig) {
    s.addText(slide.bodyText, {
      x: tmpl.bodyConfig.x, y: tmpl.bodyConfig.y,
      w: tmpl.bodyConfig.w, h: tmpl.bodyConfig.h,
      fontSize: tmpl.bodyConfig.fontSize,
      color: tmpl.bodyConfig.color,
      align: 'center',
      fontFace: 'Arial',
    });
  }

  // Branding footer
  s.addText('Generated by SAVRA AI', {
    x: 3, y: 5, w: 4, h: 0.3,
    fontSize: 10, color: COLORS.subtitle, align: 'center', fontFace: 'Arial',
  });

  // Speaker notes
  if (slide.speakerNote) {
    s.addNotes(slide.speakerNote);
  }
}

function addBulletSlide(pptx: PptxGenJS, slide: SlideData) {
  const tmpl = SLIDE_TEMPLATES['bullet-list'];
  const s = pptx.addSlide();
  s.background = { color: tmpl.background.color };

  // Accent bar
  s.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: 0.08, h: '100%',
    fill: { color: COLORS.accent },
  });

  // Title
  s.addText(slide.title, {
    x: tmpl.titleConfig.x, y: tmpl.titleConfig.y,
    w: tmpl.titleConfig.w, h: tmpl.titleConfig.h,
    fontSize: tmpl.titleConfig.fontSize,
    color: tmpl.titleConfig.color,
    bold: true,
    align: 'left',
    fontFace: 'Arial',
  });

  // Divider line
  s.addShape(pptx.ShapeType.rect, {
    x: 0.6, y: 1.15, w: 2, h: 0.03,
    fill: { color: COLORS.accent },
  });

  // Bullets
  if (slide.bullets && slide.bullets.length > 0 && tmpl.bulletConfig) {
    const bulletItems = slide.bullets.map((b: string) => ({
      text: b,
      options: {
        fontSize: tmpl.bulletConfig!.fontSize,
        color: tmpl.bulletConfig!.color,
        bullet: { code: '25CF', color: COLORS.accent },
        lineSpacing: tmpl.bulletConfig!.lineSpacing,
        fontFace: 'Arial',
        paraSpaceAfter: 8,
      },
    }));

    s.addText(bulletItems, {
      x: tmpl.bulletConfig.x, y: tmpl.bulletConfig.y,
      w: tmpl.bulletConfig.w, h: tmpl.bulletConfig.h,
    });
  }

  if (slide.speakerNote) s.addNotes(slide.speakerNote);
}

function addTwoColumnSlide(pptx: PptxGenJS, slide: SlideData) {
  const tmpl = SLIDE_TEMPLATES['two-column'];
  const s = pptx.addSlide();
  s.background = { color: tmpl.background.color };

  // Title
  s.addText(slide.title, {
    x: tmpl.titleConfig.x, y: tmpl.titleConfig.y,
    w: tmpl.titleConfig.w, h: tmpl.titleConfig.h,
    fontSize: tmpl.titleConfig.fontSize,
    color: tmpl.titleConfig.color,
    bold: true,
    align: 'center',
    fontFace: 'Arial',
  });

  // Divider line under title
  s.addShape(pptx.ShapeType.rect, {
    x: 2.5, y: 1.15, w: 5, h: 0.03,
    fill: { color: COLORS.accent },
  });

  // Left panel with background
  if (slide.leftContent && tmpl.leftPanelConfig) {
    s.addShape(pptx.ShapeType.roundRect, {
      x: tmpl.leftPanelConfig.x - 0.1, y: tmpl.leftPanelConfig.y - 0.1,
      w: tmpl.leftPanelConfig.w + 0.2, h: tmpl.leftPanelConfig.h + 0.2,
      fill: { color: 'e8e0f5' }, rectRadius: 0.15,
    });
    s.addText(slide.leftContent, {
      x: tmpl.leftPanelConfig.x, y: tmpl.leftPanelConfig.y,
      w: tmpl.leftPanelConfig.w, h: tmpl.leftPanelConfig.h,
      fontSize: tmpl.leftPanelConfig.fontSize,
      color: tmpl.leftPanelConfig.color,
      align: 'left',
      valign: 'top',
      fontFace: 'Arial',
    });
  }

  // Right panel with background
  if (slide.rightContent && tmpl.rightPanelConfig) {
    s.addShape(pptx.ShapeType.roundRect, {
      x: tmpl.rightPanelConfig.x - 0.1, y: tmpl.rightPanelConfig.y - 0.1,
      w: tmpl.rightPanelConfig.w + 0.2, h: tmpl.rightPanelConfig.h + 0.2,
      fill: { color: COLORS.darkBg }, rectRadius: 0.15,
    });
    s.addText(slide.rightContent, {
      x: tmpl.rightPanelConfig.x, y: tmpl.rightPanelConfig.y,
      w: tmpl.rightPanelConfig.w, h: tmpl.rightPanelConfig.h,
      fontSize: tmpl.rightPanelConfig.fontSize,
      color: COLORS.white,
      align: 'left',
      valign: 'top',
      fontFace: 'Arial',
    });
  }

  if (slide.speakerNote) s.addNotes(slide.speakerNote);
}

function addContentImageSlide(pptx: PptxGenJS, slide: SlideData) {
  const tmpl = SLIDE_TEMPLATES['content-with-image'];
  const s = pptx.addSlide();
  s.background = { color: tmpl.background.color };

  // Accent bar
  s.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: 0.08, h: '100%',
    fill: { color: COLORS.accent },
  });

  // Title
  s.addText(slide.title, {
    x: tmpl.titleConfig.x, y: tmpl.titleConfig.y,
    w: tmpl.titleConfig.w, h: tmpl.titleConfig.h,
    fontSize: tmpl.titleConfig.fontSize,
    color: tmpl.titleConfig.color,
    bold: true,
    align: 'left',
    fontFace: 'Arial',
  });

  // Body text
  if (slide.bodyText && tmpl.bodyConfig) {
    s.addText(slide.bodyText, {
      x: tmpl.bodyConfig.x, y: tmpl.bodyConfig.y,
      w: tmpl.bodyConfig.w, h: tmpl.bodyConfig.h,
      fontSize: tmpl.bodyConfig.fontSize,
      color: tmpl.bodyConfig.color,
      align: 'left',
      valign: 'top',
      fontFace: 'Arial',
      lineSpacing: tmpl.bodyConfig.lineSpacing,
    });
  }

  // Image placeholder (gray rounded rect with label)
  if (tmpl.rightPanelConfig) {
    s.addShape(pptx.ShapeType.roundRect, {
      x: tmpl.rightPanelConfig.x, y: tmpl.rightPanelConfig.y,
      w: tmpl.rightPanelConfig.w, h: tmpl.rightPanelConfig.h,
      fill: { color: 'e2e8f0' }, rectRadius: 0.2,
      line: { color: COLORS.subtitle, width: 1, dashType: 'dash' },
    });
    s.addText('📷 Visual Aid', {
      x: tmpl.rightPanelConfig.x, y: tmpl.rightPanelConfig.y + 1.5,
      w: tmpl.rightPanelConfig.w, h: 0.8,
      fontSize: 14, color: COLORS.subtitle, align: 'center', fontFace: 'Arial',
    });
  }

  if (slide.speakerNote) s.addNotes(slide.speakerNote);
}

function addQuoteSlide(pptx: PptxGenJS, slide: SlideData) {
  const tmpl = SLIDE_TEMPLATES['quote-or-definition'];
  const s = pptx.addSlide();
  s.background = { color: tmpl.background.color };

  // Decorative quote mark
  s.addText('"', {
    x: 0.5, y: 0.2, w: 2, h: 1.5,
    fontSize: 80, color: COLORS.accent, fontFace: 'Georgia', bold: true,
  });

  // Title (concept name)
  s.addText(slide.title, {
    x: tmpl.titleConfig.x, y: tmpl.titleConfig.y,
    w: tmpl.titleConfig.w, h: tmpl.titleConfig.h,
    fontSize: tmpl.titleConfig.fontSize,
    color: tmpl.titleConfig.color,
    bold: true,
    align: 'left',
    fontFace: 'Arial',
  });

  // Quote/definition text
  const displayText = slide.quoteText || slide.bodyText || '';
  if (displayText && tmpl.bodyConfig) {
    s.addText(displayText, {
      x: tmpl.bodyConfig.x, y: tmpl.bodyConfig.y,
      w: tmpl.bodyConfig.w, h: tmpl.bodyConfig.h,
      fontSize: tmpl.bodyConfig.fontSize,
      color: tmpl.bodyConfig.color,
      align: 'center',
      valign: 'middle',
      fontFace: 'Georgia',
      italic: true,
      lineSpacing: tmpl.bodyConfig.lineSpacing,
    });
  }

  // Accent line
  s.addShape(pptx.ShapeType.rect, {
    x: 3.5, y: 4.8, w: 3, h: 0.04,
    fill: { color: COLORS.accent },
  });

  if (slide.speakerNote) s.addNotes(slide.speakerNote);
}

export async function buildPptx(
  presentation: PresentationData,
  jobId: string,
): Promise<string> {
  const pptx = new PptxGenJS();

  // Presentation metadata
  pptx.author = 'SAVRA AI';
  pptx.company = 'Savra EdTech';
  pptx.title = presentation.presentationTitle;
  pptx.subject = 'Generated Educational Presentation';
  pptx.layout = 'LAYOUT_WIDE'; // 13.33" x 7.5"

  // Build each slide using the appropriate template
  for (const slide of presentation.slides) {
    switch (slide.slideType) {
      case 'title':
        addTitleSlide(pptx, slide);
        break;
      case 'bullet-list':
        addBulletSlide(pptx, slide);
        break;
      case 'two-column':
        addTwoColumnSlide(pptx, slide);
        break;
      case 'content-with-image':
        addContentImageSlide(pptx, slide);
        break;
      case 'quote-or-definition':
        addQuoteSlide(pptx, slide);
        break;
      default:
        // Fallback: treat unknown types as bullet slides
        addBulletSlide(pptx, slide);
    }
  }

  // Write to local file (in production, write to temp then upload to R2/S3)
  const filePath = path.join(OUTPUT_DIR, `${jobId}.pptx`);
  await pptx.writeFile({ fileName: filePath });
  console.log(`[PPTX] Built ${presentation.slides.length} slides → ${filePath}`);

  return filePath;
}
