// PPTX Builder — Template-first slide generation using pptxgenjs
// Takes structured JSON from LLM and injects into pre-designed templates
// This is the key cost optimization: LLM generates content only, layout is deterministic
import PptxGenJS from 'pptxgenjs';
import { getQuizQuestions } from '@savra/shared';
import { SLIDE_TEMPLATES, COLORS } from './templates';
import type { PresentationData, SlideData } from './shared';
import path from 'path';
import fs from 'fs';

const OUTPUT_DIR = path.join(process.cwd(), 'output');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

function addTitleSlide(pptx: PptxGenJS, slide: SlideData) {
  const tmpl = SLIDE_TEMPLATES['title'];
  const s = pptx.addSlide();
  s.background = { color: tmpl.background.color };

  // Decorative accent bar at top
  s.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: '100%', h: 0.08,
    fill: { color: COLORS.accent },
  });

  // Title
  s.addText(slide.title, {
    x: tmpl.titleConfig.x, y: tmpl.titleConfig.y,
    w: tmpl.titleConfig.w, h: tmpl.titleConfig.h,
    fontSize: tmpl.titleConfig.fontSize,
    color: tmpl.titleConfig.color,
    bold: true,
    align: 'center',
    fontFace: 'Arial',
  });

  // Subtitle
  if (slide.bodyText && tmpl.bodyConfig) {
    s.addText(slide.bodyText, {
      x: tmpl.bodyConfig.x, y: tmpl.bodyConfig.y,
      w: tmpl.bodyConfig.w, h: tmpl.bodyConfig.h,
      fontSize: tmpl.bodyConfig.fontSize,
      color: tmpl.bodyConfig.color,
      align: 'center',
      fontFace: 'Arial',
    });
  }

  // Branding footer
  s.addText('Generated by SAVRA AI', {
    x: 3, y: 5, w: 4, h: 0.3,
    fontSize: 10, color: COLORS.subtitle, align: 'center', fontFace: 'Arial',
  });

  // Speaker notes
  if (slide.speakerNote) {
    s.addNotes(slide.speakerNote);
  }
}

function addBulletSlide(pptx: PptxGenJS, slide: SlideData) {
  const tmpl = SLIDE_TEMPLATES['bullet-list'];
  const s = pptx.addSlide();
  s.background = { color: tmpl.background.color };

  // Accent bar
  s.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: 0.08, h: '100%',
    fill: { color: COLORS.accent },
  });

  // Title
  s.addText(slide.title, {
    x: tmpl.titleConfig.x, y: tmpl.titleConfig.y,
    w: tmpl.titleConfig.w, h: tmpl.titleConfig.h,
    fontSize: tmpl.titleConfig.fontSize,
    color: tmpl.titleConfig.color,
    bold: true,
    align: 'left',
    fontFace: 'Arial',
  });

  // Divider line
  s.addShape(pptx.ShapeType.rect, {
    x: 0.6, y: 1.15, w: 2, h: 0.03,
    fill: { color: COLORS.accent },
  });

  if (slide.bullets && slide.bullets.length > 0 && tmpl.bulletConfig) {
    const bulletItems = slide.bullets.map((b: string, i: number) => ({
      text: b,
      options: {
        fontSize: tmpl.bulletConfig!.fontSize,
        color: tmpl.bulletConfig!.color,
        bullet: { code: '25CF', color: COLORS.accent },
        lineSpacing: tmpl.bulletConfig!.lineSpacing,
        fontFace: 'Arial',
        paraSpaceAfter: i < slide.bullets!.length - 1 ? 10 : 4,
        indentLevel: 0,
      },
    }));

    s.addShape(pptx.ShapeType.roundRect, {
      x: 0.5, y: 1.28, w: 8.9, h: 4.15,
      fill: { color: 'FFFFFF' },
      line: { color: 'E5E7EB', width: 1 },
      rectRadius: 0.08,
    });

    s.addText(bulletItems, {
      x: tmpl.bulletConfig.x + 0.15, y: tmpl.bulletConfig.y + 0.1,
      w: tmpl.bulletConfig.w - 0.3, h: tmpl.bulletConfig.h - 0.15,
    });
  }

  if (slide.speakerNote) s.addNotes(slide.speakerNote);
}

function addQuizSlide(pptx: PptxGenJS, slide: SlideData) {
  const tmpl = SLIDE_TEMPLATES['quiz'];
  const questions = getQuizQuestions(slide).slice(0, 3);
  const s = pptx.addSlide();
  s.background = { color: tmpl.background.color };

  s.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: 0.08, h: '100%',
    fill: { color: COLORS.accent },
  });

  s.addText(slide.title, {
    x: tmpl.titleConfig.x,
    y: tmpl.titleConfig.y,
    w: tmpl.titleConfig.w,
    h: tmpl.titleConfig.h,
    fontSize: tmpl.titleConfig.fontSize,
    color: tmpl.titleConfig.color,
    bold: true,
    align: 'left',
    fontFace: 'Arial',
  });

  s.addShape(pptx.ShapeType.rect, {
    x: 0.6, y: 1.05, w: 2, h: 0.03,
    fill: { color: COLORS.accent },
  });

  const blockHeight = questions.length <= 2 ? 1.55 : 1.22;
  const startY = 1.25;

  questions.forEach((q, index) => {
    const cardY = startY + index * blockHeight;

    s.addShape(pptx.ShapeType.roundRect, {
      x: 0.55,
      y: cardY,
      w: 8.9,
      h: blockHeight - 0.12,
      fill: { color: 'FFFFFF' },
      line: { color: 'DDD6FE', width: 1 },
      rectRadius: 0.08,
    });

    s.addShape(pptx.ShapeType.roundRect, {
      x: 0.7,
      y: cardY + 0.12,
      w: 0.55,
      h: 0.38,
      fill: { color: COLORS.accent },
      rectRadius: 0.06,
    });

    s.addText(`Q${index + 1}`, {
      x: 0.7,
      y: cardY + 0.12,
      w: 0.55,
      h: 0.38,
      fontSize: 12,
      color: COLORS.white,
      bold: true,
      align: 'center',
      valign: 'middle',
      fontFace: 'Arial',
    });

    s.addText(q.question, {
      x: 1.35,
      y: cardY + 0.1,
      w: 7.9,
      h: 0.42,
      fontSize: questions.length <= 2 ? 16 : 14,
      color: COLORS.darkText,
      bold: true,
      fontFace: 'Arial',
    });

    const optionStartY = cardY + 0.52;
    q.options.slice(0, 4).forEach((option, optIndex) => {
      const letter = String.fromCharCode(65 + optIndex);
      s.addText(letter, {
        x: 0.85,
        y: optionStartY + optIndex * 0.28,
        w: 0.35,
        h: 0.26,
        fontSize: 12,
        color: COLORS.accent,
        bold: true,
        fontFace: 'Arial',
      });
      s.addText(option, {
        x: 1.25,
        y: optionStartY + optIndex * 0.28,
        w: 8.0,
        h: 0.26,
        fontSize: questions.length <= 2 ? 14 : 12,
        color: '374151',
        fontFace: 'Arial',
      });
    });
  });

  if (questions.length === 0) {
    s.addText('Add quiz questions using Populate or the editor.', {
      x: 0.8,
      y: 2,
      w: 8,
      h: 1,
      fontSize: 16,
      color: COLORS.subtitle,
      fontFace: 'Arial',
    });
  }

  if (slide.speakerNote) s.addNotes(slide.speakerNote);
}

function addTwoColumnSlide(pptx: PptxGenJS, slide: SlideData) {
  const tmpl = SLIDE_TEMPLATES['two-column'];
  const s = pptx.addSlide();
  s.background = { color: tmpl.background.color };

  s.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: 0.08, h: '100%',
    fill: { color: COLORS.accent },
  });

  s.addText(slide.title, {
    x: tmpl.titleConfig.x, y: tmpl.titleConfig.y,
    w: tmpl.titleConfig.w, h: tmpl.titleConfig.h,
    fontSize: tmpl.titleConfig.fontSize,
    color: tmpl.titleConfig.color,
    bold: true,
    align: 'center',
    fontFace: 'Arial',
  });

  s.addShape(pptx.ShapeType.rect, {
    x: 2.5, y: 1.15, w: 5, h: 0.03,
    fill: { color: COLORS.accent },
  });

  const isDiscussion = /discuss|think|pair|prompt|activity/i.test(slide.title + slide.leftContent + slide.rightContent);

  if (slide.leftContent && tmpl.leftPanelConfig) {
    s.addShape(pptx.ShapeType.roundRect, {
      x: tmpl.leftPanelConfig.x - 0.1, y: tmpl.leftPanelConfig.y - 0.1,
      w: tmpl.leftPanelConfig.w + 0.2, h: tmpl.leftPanelConfig.h + 0.2,
      fill: { color: 'EDE9FE' }, rectRadius: 0.12,
      line: { color: 'DDD6FE', width: 1 },
    });
    s.addText(isDiscussion ? 'Prompt' : 'Column A', {
      x: tmpl.leftPanelConfig.x, y: tmpl.leftPanelConfig.y - 0.05,
      w: tmpl.leftPanelConfig.w, h: 0.35,
      fontSize: 11, color: COLORS.accent, bold: true, fontFace: 'Arial',
    });
    s.addText(slide.leftContent, {
      x: tmpl.leftPanelConfig.x, y: tmpl.leftPanelConfig.y + 0.35,
      w: tmpl.leftPanelConfig.w, h: tmpl.leftPanelConfig.h - 0.35,
      fontSize: tmpl.leftPanelConfig.fontSize,
      color: tmpl.leftPanelConfig.color,
      align: 'left',
      valign: 'top',
      fontFace: 'Arial',
      lineSpacing: 22,
    });
  }

  if (slide.rightContent && tmpl.rightPanelConfig) {
    s.addShape(pptx.ShapeType.roundRect, {
      x: tmpl.rightPanelConfig.x - 0.1, y: tmpl.rightPanelConfig.y - 0.1,
      w: tmpl.rightPanelConfig.w + 0.2, h: tmpl.rightPanelConfig.h + 0.2,
      fill: { color: COLORS.darkBg }, rectRadius: 0.12,
      line: { color: COLORS.accent, width: 1 },
    });
    s.addText(isDiscussion ? 'Discuss / Answers' : 'Column B', {
      x: tmpl.rightPanelConfig.x, y: tmpl.rightPanelConfig.y - 0.05,
      w: tmpl.rightPanelConfig.w, h: 0.35,
      fontSize: 11, color: COLORS.highlight, bold: true, fontFace: 'Arial',
    });
    s.addText(slide.rightContent, {
      x: tmpl.rightPanelConfig.x, y: tmpl.rightPanelConfig.y + 0.35,
      w: tmpl.rightPanelConfig.w, h: tmpl.rightPanelConfig.h - 0.35,
      fontSize: tmpl.rightPanelConfig.fontSize,
      color: COLORS.white,
      align: 'left',
      valign: 'top',
      fontFace: 'Arial',
      lineSpacing: 22,
    });
  }

  if (slide.speakerNote) s.addNotes(slide.speakerNote);
}

function addContentImageSlide(pptx: PptxGenJS, slide: SlideData) {
  const tmpl = SLIDE_TEMPLATES['content-with-image'];
  const s = pptx.addSlide();
  s.background = { color: tmpl.background.color };

  // Accent bar
  s.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: 0.08, h: '100%',
    fill: { color: COLORS.accent },
  });

  // Title
  s.addText(slide.title, {
    x: tmpl.titleConfig.x, y: tmpl.titleConfig.y,
    w: tmpl.titleConfig.w, h: tmpl.titleConfig.h,
    fontSize: tmpl.titleConfig.fontSize,
    color: tmpl.titleConfig.color,
    bold: true,
    align: 'left',
    fontFace: 'Arial',
  });

  // Body text
  if (slide.bodyText && tmpl.bodyConfig) {
    s.addText(slide.bodyText, {
      x: tmpl.bodyConfig.x, y: tmpl.bodyConfig.y,
      w: tmpl.bodyConfig.w, h: tmpl.bodyConfig.h,
      fontSize: tmpl.bodyConfig.fontSize,
      color: tmpl.bodyConfig.color,
      align: 'left',
      valign: 'top',
      fontFace: 'Arial',
      lineSpacing: tmpl.bodyConfig.lineSpacing,
    });
  }

  if (tmpl.rightPanelConfig) {
    const px = tmpl.rightPanelConfig.x;
    const py = tmpl.rightPanelConfig.y;
    const pw = tmpl.rightPanelConfig.w;
    const ph = tmpl.rightPanelConfig.h;

    s.addShape(pptx.ShapeType.roundRect, {
      x: px, y: py, w: pw, h: ph,
      fill: { color: 'F8FAFC' },
      rectRadius: 0.15,
      line: { color: 'CBD5E1', width: 1.5, dashType: 'dash' },
    });
    s.addShape(pptx.ShapeType.roundRect, {
      x: px + 0.35, y: py + 0.5, w: pw - 0.7, h: ph - 2.2,
      fill: { color: 'EDE9FE' },
      rectRadius: 0.1,
    });
    s.addShape(pptx.ShapeType.rect, {
      x: px + pw * 0.25, y: py + 1.1, w: pw * 0.5, h: 0.06,
      fill: { color: COLORS.accent },
    });
    s.addShape(pptx.ShapeType.rect, {
      x: px + pw * 0.2, y: py + 1.5, w: pw * 0.6, h: 1.2,
      fill: { color: 'DDD6FE' },
    });
    s.addText('Visual', {
      x: px, y: py + 0.65, w: pw, h: 0.4,
      fontSize: 13, color: COLORS.accent, bold: true, align: 'center', fontFace: 'Arial',
    });
    s.addText('Diagram / image', {
      x: px, y: py + 2.85, w: pw, h: 0.5,
      fontSize: 12, color: COLORS.subtitle, align: 'center', fontFace: 'Arial',
    });
    s.addText('Add board sketch or textbook figure in class', {
      x: px, y: py + ph - 0.55, w: pw, h: 0.35,
      fontSize: 9, color: COLORS.subtitle, align: 'center', italic: true, fontFace: 'Arial',
    });
  }

  if (slide.speakerNote) s.addNotes(slide.speakerNote);
}

function addQuoteSlide(pptx: PptxGenJS, slide: SlideData) {
  const tmpl = SLIDE_TEMPLATES['quote-or-definition'];
  const s = pptx.addSlide();
  s.background = { color: tmpl.background.color };

  // Decorative quote mark
  s.addText('"', {
    x: 0.5, y: 0.2, w: 2, h: 1.5,
    fontSize: 80, color: COLORS.accent, fontFace: 'Georgia', bold: true,
  });

  // Title (concept name)
  s.addText(slide.title, {
    x: tmpl.titleConfig.x, y: tmpl.titleConfig.y,
    w: tmpl.titleConfig.w, h: tmpl.titleConfig.h,
    fontSize: tmpl.titleConfig.fontSize,
    color: tmpl.titleConfig.color,
    bold: true,
    align: 'left',
    fontFace: 'Arial',
  });

  const displayText = slide.quoteText || slide.bodyText || '';
  if (displayText && tmpl.bodyConfig) {
    s.addShape(pptx.ShapeType.roundRect, {
      x: 0.9, y: 1.55, w: 8.5, h: 3.35,
      fill: { color: '1F2937' },
      line: { color: COLORS.accent, width: 1 },
      rectRadius: 0.1,
    });
    s.addText(displayText, {
      x: tmpl.bodyConfig.x, y: tmpl.bodyConfig.y,
      w: tmpl.bodyConfig.w, h: tmpl.bodyConfig.h,
      fontSize: tmpl.bodyConfig.fontSize,
      color: tmpl.bodyConfig.color,
      align: 'center',
      valign: 'middle',
      fontFace: 'Georgia',
      italic: true,
      lineSpacing: tmpl.bodyConfig.lineSpacing,
    });
  }

  // Accent line
  s.addShape(pptx.ShapeType.rect, {
    x: 3.5, y: 4.8, w: 3, h: 0.04,
    fill: { color: COLORS.accent },
  });

  if (slide.speakerNote) s.addNotes(slide.speakerNote);
}

export async function buildPptx(
  presentation: PresentationData,
  jobId: string,
): Promise<string> {
  const pptx = new PptxGenJS();

  // Presentation metadata
  pptx.author = 'SAVRA AI';
  pptx.company = 'Savra EdTech';
  pptx.title = presentation.presentationTitle;
  pptx.subject = 'Generated Educational Presentation';
  pptx.layout = 'LAYOUT_WIDE'; // 13.33" x 7.5"

  // Build each slide using the appropriate template
  for (const slide of presentation.slides) {
    switch (slide.slideType) {
      case 'title':
        addTitleSlide(pptx, slide);
        break;
      case 'quiz':
        addQuizSlide(pptx, slide);
        break;
      case 'bullet-list':
        if (getQuizQuestions(slide).length > 0 && /quiz|mcq|check/i.test(slide.title)) {
          addQuizSlide(pptx, slide);
        } else {
          addBulletSlide(pptx, slide);
        }
        break;
      case 'two-column':
        addTwoColumnSlide(pptx, slide);
        break;
      case 'content-with-image':
        addContentImageSlide(pptx, slide);
        break;
      case 'quote-or-definition':
        addQuoteSlide(pptx, slide);
        break;
      default:
        // Fallback: treat unknown types as bullet slides
        addBulletSlide(pptx, slide);
    }
  }

  // Write to local file (in production, write to temp then upload to R2/S3)
  const filePath = path.join(OUTPUT_DIR, `${jobId}.pptx`);
  await pptx.writeFile({ fileName: filePath });
  console.log(`[PPTX] Built ${presentation.slides.length} slides → ${filePath}`);

  return filePath;
}
